### ISSUE TITLE
Client crash when a ComponentTrack is added

### ISSUE THREAD

**Issue by Jdyn** [jellyfish-dev/react-client-sdk#72]
When adding a FileComponent server side to the room with something like
```elixir
Room.add_component(client, room_id, %Jellyfish.Component.File{ file_path: path })
```
As soon as the `Jellyfish.Notification.ComponentTrackAdded` is emitted and the track is sent to the client, the react client crashes due to this access in `onTrackEncodingChanged`

```ts
export const onTrackEncodingChanged = (prevState, peerId, trackId, encoding) => {
    const peer = prevState.remote[peerId];
    const peerTrack = { ...peer.tracks[trackId], encoding };
    ...                         ^^^^^^
};
```
logs:
```elixir
Uncaught TypeError: Cannot read properties of undefined (reading 'tracks')
    at onTrackEncodingChanged (stateMappers.js:147:33)
    at onEncodingChanged (stateMappers.js:322:12)

The above error occurred in the <JellyfishContextProvider>
```

**Comment by kamil-stasiak** [comment]
Hey, thanks for the report. We'll take care of it as quickly as possible
